const User = require("../models/user");
const Dipendenti = require("../models/dipendenti");
const express = require("express");
const redis = require("redis");
const { ObjectId } = require("bson");
const bcrypt = require('bcrypt');
const router = express.Router();
const Log = require("../models/log");

const redisTimeCache = parseInt(process.env.REDISTTL) || 60;

// Funzione helper per generare username (es. "mario alfio Di Grazia" -> "marioalfio.digrazia")
function generaUsername(nome, cognome) {
    const nomeClean = (nome || "").replace(/\s+/g, "").toLowerCase();
    const cognomeClean = (cognome || "").replace(/\s+/g, "").toLowerCase();
    return `${nomeClean}.${cognomeClean}`;
}

function generaPasswordCasuale(lunghezza = 8) {
    const caratteri = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    let password = '';
    for (let i = 0; i < lunghezza; i++) {
        password += caratteri.charAt(Math.floor(Math.random() * caratteri.length));
    }
    return password;
}

router.get("/", async (req, res) => {
    try {
        const getData = () => {
            return Dipendenti.find();
        };

        const dipendenti = await getData();
        res.status(200).json(dipendenti);
    } catch (err) {
        console.error("Error: ", err);
        res.status(500).json({ Error: err });
    }
});

// http://[HOST]:[PORT]/api/dipendenti/[ID_DIPENDENTE]
router.get("/:id", async (req, res) => {
    const { id } = req.params;
    try {
        const getData = () => {
            return Dipendenti.findById(id);
        };

        const dipendenti = await getData();
        res.status(200).json(dipendenti);
    } catch (err) {
        res.status(500).json({ Error: err });
    }
});

// http://[HOST]:[PORT]/api/dipendenti/byuser/[ID_USER]
router.get("/byuser/:id", async (req, res) => {
    const { id } = req.params;
    try {
        const getData = async () => {
            return await Dipendenti.find({ _id: id });
        };

        const dipendenti = await getData();
        res.status(200).json(dipendenti);
    } catch (err) {
        res.status(500).json({ Error: err.message });
    }
});

async function codificaPassword(password) {
    const saltRounds = 12;
    try {
        const hash = await bcrypt.hash(password, saltRounds);
        return hash;
    } catch (err) {
        console.error("Errore nella codifica della password:", err);
        throw err;
    }
}

// http://[HOST]:[PORT]/api/dipendenti (POST)
// INSERT dipendente su DB
router.post("/", async (req, res) => {
    try {
        const newDip = req.body.dipendente;

        if (!newDip.email || !newDip.mansione) {
            return res.status(400).json({ Error: 'Email or Mansione not defined' });
        }

        // Genera username nel formato nome.cognome (senza spazi e minuscolo)
        const customUsername = generaUsername(newDip.nome, newDip.cognome);

        // Genera e codifica la password mantenendo la logica originaria
        const passwordAutoGenerated = generaPasswordCasuale(8);
        const pwd = await codificaPassword(passwordAutoGenerated);

        // Crea e salva il nuovo dipendente
        const dipendente = new Dipendenti(newDip);
        const result = await dipendente.save();

        // Crea e salva il nuovo utente associato al customUsername
        const user = new User({
            username: customUsername,
            password: pwd,
            active: true,
            role: newDip.mansione,
            dipendenteID: result._id,
            firma: result.nome + " " + result.cognome
        });
        const userResult = await user.save();

        // Mailer SMTP (Invio Diretto)
        const clientMailerService = req.app.get("mailer");
        const clientMailerDisabled = req.app.get("mailerDisabled");

        console.log("clientMailerDisabled: ", clientMailerDisabled);
        if (clientMailerService && !clientMailerDisabled) {
            console.log("Pronto per invio mail a:", newDip.email);

            const emailSubject = "Creazione Account - Credenziali di Accesso";
            const emailHtmlBody = `
                <h2>Benvenuto/a ${newDip.nome} ${newDip.cognome},</h2>
                <p>Il tuo account e\' stato creato con successo all'interno del sistema.</p>
                <p>Ecco le tue credenziali per effettuare il primo accesso:</p>
                <ul>
                    <li><strong>Username:</strong> ${customUsername}</li>
                    <li><strong>Password temporanea:</strong> ${passwordAutoGenerated}</li>
                </ul>
                <p>Ti consigliamo di cambiare la password al primo accesso.</p>
                <br>
                <p>Cordiali saluti,<br><em>Lo Staff</em></p>
            `;

            const mailOptions = {
                from: process.env.SMTP_FROM || '"Gestionale Personale - La Rinascita" <innovawaresrl@gmail.com>',
                to: newDip.email,
                subject: emailSubject,
                html: emailHtmlBody
            };

            clientMailerService.sendMail(mailOptions, (error, info) => {
                if (error) {
                    console.error("Errore durante l'invio dell'email via SMTP:", error);
                } else {
                    console.log("Email inviata con successo! ID messaggio:", info.messageId);
                }
            });
        }

        const usr = res.locals.auth;

        const getDipendente = () => {
            return Dipendenti.findById(usr.dipendenteID);
        };

        const dip = await getDipendente();

        const log = new Log({
            data: new Date(),
            operatore: dip.nome + " " + dip.cognome,
            operatoreID: usr.dipendenteID,
            className: "Dipendente",
            operazione: "Inserimento dipendente: " + dipendente.cognome + " " + dipendente.nome,
        });
        console.log("log: ", log);
        const resultLog = await log.save();

        res.status(200).json(result);
    } catch (err) {
        console.error("Errore durante l'inserimento del dipendente:", err);
        res.status(500).json({ Error: err.message || 'Errore interno del server' });
    }
});

// http://[HOST]:[PORT]/api/dipendenti/[ID_DIPENDENTE]
// Modifica del dipendente
router.put("/:id", async (req, res) => {
    try {
        const { id } = req.params;
        const { dipendente } = req.body;

        console.log('accettatoRegolamento: ' + dipendente.accettatoRegolamento);
        console.log('idUser: ' + dipendente.idUser);

        const dipendenti = await Dipendenti.updateOne(
            { _id: id },
            { $set: dipendente }
        );

        console.log("Update Dipendente: ", dipendenti);

        console.log("Update Dipendente User:",
            await User.updateOne(
                { dipendenteID: dipendente._id },
                { $set: { role: dipendente.mansione } }
            )
        );

        const usr = res.locals.auth;

        const getDipendente = () => {
            return Dipendenti.findById(usr.dipendenteID);
        };

        const dip = await getDipendente();

        const log = new Log({
            data: new Date(),
            operatore: dip.nome + " " + dip.cognome,
            operatoreID: usr.dipendenteID,
            className: "Dipendente",
            operazione: "Modifica dipendente: " + dipendente.cognome + " " + dipendente.nome,
        });
        console.log("log: ", log);
        const resultLog = await log.save();

        res.status(200).json(dipendenti);
    } catch (err) {
        res.status(500).json({ Error: err });
    }
});

// DELETE dipendente e la sua utenza associata
router.delete("/:id", async (req, res) => {
    try {
        const { id } = req.params;

        // 1. Elimina l'utenza associata al dipendente
        const deletedUser = await User.deleteOne({ dipendenteID: id });
        console.log("Utente eliminato:", deletedUser);

        // 2. Elimina il dipendente
        const dipendente = await Dipendenti.findByIdAndDelete(id);

        redisClient = req.app.get("redis");
        redisDisabled = req.app.get("redisDisabled");

        if (redisClient != undefined && !redisDisabled) {
            let searchTerm = `DIPENDENTEBY${id}`;
            redisClient.del(searchTerm);
            searchTerm = `DIPENDENTE${id}`;
            redisClient.del(searchTerm);
        }

        const usr = res.locals.auth;

        const getDipendente = () => {
            return Dipendenti.findById(usr.dipendenteID);
        };

        const dip = await getDipendente();

        const log = new Log({
            data: new Date(),
            operatore: dip.nome + " " + dip.cognome,
            operatoreID: usr.dipendenteID,
            className: "Dipendente",
            operazione: "Eliminazione dipendente: " + (dipendente ? dipendente.cognome + " " + dipendente.nome : id),
        });
        console.log("log: ", log);
        const resultLog = await log.save();

        res.status(200).json({
            message: "Dipendente e utenza associata eliminati con successo",
            dipendente: dipendente
        });
    } catch (err) {
        console.error("Errore durante l'eliminazione del dipendente/utente:", err);
        res.status(500).json({ Error: err.message || err });
    }
});

module.exports = router;